# Generated by Django 4.2.30 on 2026-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ar_model_usdz',
            field=models.FileField(blank=True, null=True, upload_to='ar_models/'),
        ),
    ]
