# Generated by Django 4.2.30 on 2026-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitem_ar_model_usdz'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
