# Generated by Django 4.2.30 on 2026-06-25 10:29

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_is_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ar_model_file',
            field=models.FileField(blank=True, null=True, storage=restaurants.models._ar_storage, upload_to='ar_models/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ar_model_usdz',
            field=models.FileField(blank=True, null=True, storage=restaurants.models._ar_storage, upload_to='ar_models/'),
        ),
    ]
